/**
 * On-Call demo customer skins.
 *
 * A skin generates ONE customer-branded product page for a specific prospect
 * without touching any mechanics. /oncall/c/<slug> serves the skin's chosen
 * vertical page (skin.vertical) rebranded with the customer's name, mark, and
 * theme, with the on-call shim active — that single URL is what a DE shares.
 * /oncall/c/<slug>/report serves the matching branded support portal, and
 * /oncall/c/<slug>/incident serves an opted-in incident console. The alerts
 * surface is enabled by default; bugPortal and incident are optional opt-in
 * surfaces. An incident may optionally define chatter.vocabulary as a flat
 * source-phrase-to-replacement map. The generic /oncall hub itself is never
 * skinned. Adding a customer = adding one entry here.
 *
 * Two separate theme keys, one per surface: page.theme themes the stock
 * vertical page served through the brand shim, while the top-level theme
 * themes the report portal and incident console. For stock-page skins without
 * page.file, the top-level theme falls back into the page shim too, so a
 * stock-page skin needs just one theme block. A natively branded page keeps
 * its own palette and is never overridden by the portal theme; set page.theme
 * only when the page needs different variables from the portal surfaces.
 *
 * Slugs are anonymous 8-char hex ids (generate with `openssl rand -hex 4`),
 * never the customer's name, so shared URLs don't leak who a demo is for.
 * Customer names appear only in rendered copy values, not in slugs, keys,
 * identifiers, or comments.
 *
 * What we deliberately do NOT personalize: telemetry service names, monitor
 * queries' service tags, and repo references in Slack investigation copy —
 * the responder investigates the repo that REPO_URL (app/services/oncall.js)
 * points at, so those must stay truthful for the investigation to be
 * believable.
 *
 * Bug portal templates reference existing BUG_CATALOG template ids (see
 * app/services/oncall.js) so backend-symptom reports keep activating the
 * matching real degradation; only the customer-facing copy changes.
 *
 * A skin may set trigger: { kind: 'bug', templateId, persona, severity,
 * productArea } to make its page's primary action file a human-style support
 * ticket in #oncall-bugs (via /api/oncall/bug) instead of posting the
 * monitor-style alert card to #oncall-alerts. templateId must exist in
 * BUG_CATALOG. Two skins can share one page file to offer both flavors.
 *
 * A skin may set devinSession: { auto: true, orgId, userId, apiKey } to have
 * its own alerts create a Devin investigation session immediately and reply
 * with the session link in the alert thread. Alerts raised from the generic
 * hub, or from skins without this key, stay alert-only. orgId defaults to
 * DEVIN_ORG_ID and the credential to DEVIN_ONCALL_SERVICE_KEY /
 * DEVIN_SERVICE_KEY / DEVIN_API_KEY; never put a credential in this file.
 *
 * A skin may set sonarPR: { auto: true, customer } to have each of its alerts
 * also open the SonarCloud remediation demo PR (app/services/sonar-pr-trigger.js)
 * in that customer's configured target repo, the same way the legacy
 * event-driven alert flow does. customer defaults to 'default'; the GitHub
 * token comes from the environment.
 *
 * A skin may set hideRibbon: true to suppress the floating demo ribbon and its
 * collapsed dot; rerouting and alert posting are unaffected.
 *
 * A native page whose primary action has no legacy /api/<vertical> endpoint
 * (only the on-call one) sets oncallOnly: true, so its direct /<page-slug>
 * URL is served with the shim instead of as a bare page whose action 404s.
 *
 * Skins are direct-URL only: the stock /oncall hub never lists customers,
 * and each skin is reachable solely by its own /oncall/c/<slug> URL.
 */

const ONCALL_SKINS = {
  '76bc90d0': {
    slug: '76bc90d0',
    company: 'Charles Schwab',
    brandMark: 'S',
    vertical: 'banking',
    oncallOnly: true,
    page: { file: '76bc90d0.html', title: 'Move Money | Charles Schwab' },
    theme: {
      '--accent': '#00A0DF',
      '--ink': '#16242F',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#003057',
      '--chrome-text': '#FFFFFF',
    },
    supportCenter: 'Charles Schwab Support',
    disclaimer: 'NOT ACTUALLY A CHARLES SCHWAB SITE — internal demo only, not affiliated with, endorsed by, or a real Charles Schwab product.',
  },
  'd82eca33': {
    slug: 'd82eca33',
    company: 'Toast',
    brandMark: 'T',
    vertical: 'marketplace',
    oncallOnly: true,
    page: {
      file: 'd82eca33.html',
      title: 'Summer Street Kitchen | Online Ordering | Toast Local',
    },
    theme: {
      '--accent': '#FF4C00',
      '--ink': '#252525',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#1F1F1F',
      '--chrome-text': '#FFFFFF',
    },
    supportCenter: 'Toast Guest Support',
    disclaimer: 'NOT ACTUALLY A TOAST SITE — internal demo only, not affiliated with, endorsed by, or a real Toast product.',
  },
  '857b6424': {
    slug: '857b6424',
    company: 'Qdoba',
    brandMark: 'Q',
    vertical: 'marketplace',
    hideRibbon: true,
    oncallOnly: true,
    page: {
      file: '857b6424.html',
      title: 'Chicken Queso Bowl | QDOBA Mexican Eats',
    },
    accent: '#F09800',
    accentDark: '#D78700',
    supportCenter: 'QDOBA Guest Support',
    supportCenterSub: 'Online Ordering',
    disclaimer: 'NOT ACTUALLY A QDOBA SITE — internal demo only, not affiliated with, endorsed by, or a real Qdoba product.',
  },
  '63dbb52f': {
    slug: '63dbb52f',
    company: 'Kaufland',
    brandMark: 'K',
    vertical: 'marketplace',
    hideRibbon: true,
    oncallOnly: true,
    page: {
      file: '63dbb52f.html',
      title: 'Philips Airfryer Serie 2000, 4,2l, RapidAir, Digital, schwarz (NA221/00) | Kaufland.de',
    },
    accent: '#E10915',
    accentDark: '#C00811',
    theme: {
      '--accent': '#E10915',
      '--ink': '#1A1A1A',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#E10915',
      '--chrome-text': '#FFFFFF',
    },
    supportCenter: 'Kaufland Kundenservice',
    supportCenterSub: 'Online-Marktplatz Support',
    disclaimer: 'NOT ACTUALLY A KAUFLAND SITE — internal demo only, not affiliated with, endorsed by, or a real Kaufland product.',
    bugPortal: {
      products: [
        {
          area: 'marketplace',
          label: 'Kaufland Online-Marktplatz \u2014 Warenkorb',
          persona: { name: 'Lena Hoffmann', email: 'lena.hoffmann@brightmail.io', sev: 'High' },
          templates: [
            {
              id: 'marketplace-cart-timeout',
              label: 'Add to cart fails with a timeout',
              sev: 'High',
              text: 'Shoppers cannot put marketplace items in the basket. You press "In den Warenkorb", the button spins for about eight seconds and then an error comes back saying the item could not be reserved. Same product, same seller, every attempt.',
            },
            {
              id: 'marketplace-campaign-conversion',
              label: 'Campaign traffic converting at zero',
              sev: 'Critical',
              text: 'Escalating from trading: the weekend kitchen-appliance campaign is live, traffic is fine and product pages load, but basket adds have collapsed to almost nothing. Every add we try ourselves spins for ages and then errors out. We are burning media spend on a storefront that cannot take an order.',
            },
          ],
        },
      ],
    },
  },
  '5eae08bb': {
    slug: '5eae08bb',
    company: 'Tyk',
    brandMark: 'T',
    vertical: 'hightech',
    page: {
      file: '5eae08bb.html',
      title: 'Tyk Cloud — Team access',
    },
    theme: {
      '--accent': '#8438FA',
      '--ink': '#140527',
      '--surface': '#FEF9FF',
      '--chrome-bg': '#08051C',
      '--chrome-text': '#FEF9FF',
    },
    supportCenter: 'Tyk Support',
    disclaimer: 'NOT ACTUALLY A TYK SITE — internal demo only, not affiliated with, endorsed by, or a real Tyk product.',
  },
  '0f76667b': {
    slug: '0f76667b',
    company: 'Abacum',
    brandMark: 'A',
    vertical: 'hightech',
    page: {
      file: '0f76667b.html',
      title: 'Abacum — Workspace seats',
    },
    theme: {
      '--accent': '#7700FE',
      '--ink': '#0D0D0D',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#000000',
      '--chrome-text': '#FFFFFF',
    },
    supportCenter: 'Abacum Support',
    disclaimer: 'NOT ACTUALLY AN ABACUM SITE — internal demo only, not affiliated with, endorsed by, or a real Abacum product.',
  },
  '66cee815': {
    slug: '66cee815',
    company: 'JFrog',
    brandMark: 'J',
    vertical: 'hightech',
    page: {
      file: '66cee815.html',
      title: 'JFrog Platform — Project access',
    },
    theme: {
      '--accent': '#36A13B',
      '--ink': '#2F2F2F',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#080C25',
      '--chrome-text': '#E4E9EA',
    },
    supportCenter: 'JFrog Support',
    disclaimer: 'NOT ACTUALLY A JFROG SITE — internal demo only, not affiliated with, endorsed by, or a real JFrog product.',
  },
  'cb414550': {
    slug: 'cb414550',
    company: 'Arcadia',
    brandMark: 'A',
    vertical: 'banking',
    page: {
      // Natively branded custom page: served instead of the vertical's stock
      // page; the brand shim skips the title/logo rewrite for it.
      file: 'cb414550.html',
      title: 'Arcadia — Utility Bill Pay',
    },
    accent: '#0FFF87',
    accentDark: '#0be27a',
    theme: {
      '--accent': '#104336',
      '--ink': '#104336',
      '--surface': '#F9F3E8',
      '--chrome-bg': '#101F1E',
      '--chrome-text': '#F9F3E8',
    },
    supportCenter: 'Arcadia Support',
    supportCenterSub: 'Customer Care & Incident Intake',
    disclaimer: 'NOT ACTUALLY AN ARCADIA SITE — internal demo only, not affiliated with, endorsed by, or a real Arcadia product.',
  },
  '11c8bdaf': {
    slug: '11c8bdaf',
    company: 'Fujitsu',
    brandMark: 'F',
    vertical: 'hightech',
    page: {
      file: '11c8bdaf.html',
      title: 'Fujitsu Kozuchi — Workspace access | Fujitsu Global',
    },
    theme: {
      '--accent': '#EA0000',
      '--ink': '#000000',
      '--surface': '#ffffff',
      '--chrome-bg': '#3C3C3C',
      '--chrome-text': '#ffffff',
    },
    supportCenter: 'Fujitsu Support',
    disclaimer: 'NOT ACTUALLY A FUJITSU SITE — internal demo only, not affiliated with, endorsed by, or a real Fujitsu product.',
  },
  '8cc190d2': {
    slug: '8cc190d2',
    company: 'Brex',
    brandMark: 'B',
    vertical: 'banking',
    page: {
      // Natively branded custom page: served instead of the vertical's stock
      // page; the brand shim skips the title/logo rewrite for it.
      file: '8cc190d2.html',
      title: 'Brex — Business Banking',
    },
    accent: '#FF3D00',
    accentDark: '#d93400',
    theme: {
      '--accent': '#FF3D00',
      '--ink': '#15191E',
      '--surface': '#ffffff',
      '--chrome-bg': '#000710',
      '--chrome-text': '#fcfcfd',
    },
    supportCenter: 'Brex Support',
    supportCenterSub: 'Customer Care & Incident Intake',
    disclaimer: 'NOT ACTUALLY A BREX SITE — internal demo only, not affiliated with, endorsed by, or a real Brex product.',
    bugPortal: {
      products: [
        {
          area: 'banking',
          label: 'Brex Business Account \u2014 Transfers',
          persona: { name: 'Dana Whitfield', email: 'dana.whitfield@brightmail.io', sev: 'High' },
          templates: [
            {
              id: 'banking-transfer-slow',
              label: 'Transfers extremely slow',
              sev: 'High',
              text: 'Hey team \u2014 transfers from the business account take about ten seconds now. The spinner sits there on every single transfer before it finally completes. Any amount, both accounts. Multiple people on our side hit this today.',
            },
            {
              id: 'banking-payroll-cutoff',
              label: 'Payroll batch missing cutoff',
              sev: 'Critical',
              text: 'Escalating: our payroll batch runs transfers one after another and each one now takes ~10 seconds, so the batch will miss the wire cutoff. Nothing errors \u2014 it is just painfully slow, and it was fine on Friday. Please treat as urgent.',
            },
          ],
        },
      ],
    },
  },
  '8bdcfab6': {
    slug: '8bdcfab6',
    company: 'Robinhood',
    brandMark: 'R',
    vertical: 'banking',
    page: {
      // Natively branded custom page: served instead of the vertical's stock
      // page; the brand shim skips the title/logo rewrite for it.
      file: '8bdcfab6.html',
      title: 'Robinhood Banking',
    },
    accent: '#00C805',
    accentDark: '#00a304',
    theme: {
      '--accent': '#00C805',
      '--ink': '#111111',
      '--surface': '#ffffff',
      '--chrome-bg': '#000000',
      '--chrome-text': '#ffffff',
    },
    supportCenter: 'Robinhood Support',
    supportCenterSub: 'Customer Care & Incident Intake',
    disclaimer: 'NOT ACTUALLY A ROBINHOOD SITE — internal demo only, not affiliated with, endorsed by, or a real Robinhood product.',
    bugPortal: {
      products: [
        {
          area: 'banking',
          label: 'Robinhood Banking \u2014 Transfers',
          persona: { name: 'Marcus Delgado', email: 'marcus.delgado@brightmail.io', sev: 'High' },
          templates: [
            {
              id: 'banking-transfer-slow',
              label: 'Transfers stuck on a spinner',
              sev: 'High',
              text: 'Transfers between my banking and brokerage accounts are supposed to be instant, but every transfer sits on a spinner for about ten seconds before it completes. Tried different amounts and both directions \u2014 same thing every time. Started today.',
            },
            {
              id: 'banking-payroll-cutoff',
              label: 'Recurring transfers running late',
              sev: 'Critical',
              text: 'Escalating: my scheduled recurring transfers run one after another and each one now takes ~10 seconds, so the whole batch is finishing way later than usual. Nothing fails \u2014 it is just painfully slow, and it was fine yesterday. During market hours this really matters.',
            },
          ],
        },
      ],
    },
  },
  'df1b99c6': {
    slug: 'df1b99c6',
    company: 'Bilt Rewards',
    brandMark: 'B',
    vertical: 'banking',
    page: {
      file: 'df1b99c6.html',
      title: 'Bilt — Pay rent, earn points',
    },
    accent: '#97c6ea',
    accentDark: '#6fa9d6',
    theme: {
      '--accent': '#6fa9d6',
      '--ink': '#010a13',
      '--surface': '#fbfbfb',
      '--chrome-bg': '#010a13',
      '--chrome-text': '#fafafa',
    },
    supportCenter: 'Bilt Support',
    supportCenterSub: 'Member Care & Incident Intake',
    disclaimer: 'NOT ACTUALLY A BILT REWARDS SITE — internal demo only, not affiliated with, endorsed by, or a real Bilt Rewards product.',
  },
  '70d04b0f': {
    slug: '70d04b0f',
    company: 'Cyera',
    brandMark: 'C',
    vertical: 'hightech',
    page: {
      // Natively branded custom page: served instead of the vertical's stock
      // page; the brand shim skips the title/logo rewrite for it.
      file: '70d04b0f.html',
      title: 'Cyera — Data Security Platform',
    },
    accent: '#6D2D93',
    accentDark: '#441363',
    theme: {
      '--accent': '#6D2D93',
      '--ink': '#160923',
      '--surface': '#ffffff',
      '--chrome-bg': '#160923',
      '--chrome-text': '#f6f5f1',
    },
    supportCenter: 'Cyera Support',
    supportCenterSub: 'Customer Care & Incident Intake',
    disclaimer: 'NOT ACTUALLY A CYERA SITE — internal demo only, not affiliated with, endorsed by, or a real Cyera product.',
  },
  'cbb43fd1': {
    slug: 'cbb43fd1',
    company: 'Celonis',
    brandMark: 'C',
    vertical: 'hightech',
    page: {
      // Natively branded custom page: served instead of the vertical's stock
      // page; the brand shim skips the title/logo rewrite for it.
      file: 'cbb43fd1.html',
      title: 'Celonis — Team Administration',
    },
    accent: '#5CFE50',
    accentDark: '#3fd634',
    theme: {
      '--accent': '#3fd634',
      '--ink': '#111111',
      '--surface': '#ffffff',
      '--chrome-bg': '#000000',
      '--chrome-text': '#ffffff',
    },
    supportCenter: 'Celonis Support',
    supportCenterSub: 'Customer Care & Incident Intake',
    disclaimer: 'NOT ACTUALLY A CELONIS SITE — internal demo only, not affiliated with, endorsed by, or a real Celonis product.',
  },
  '71dff37b': {
    slug: '71dff37b',
    company: 'Point72',
    brandMark: 'P',
    vertical: 'banking',
    page: {
      // Natively branded custom page: served instead of the vertical's stock
      // page; the brand shim skips the title/logo rewrite for it.
      file: '71dff37b.html',
      title: 'Point72 — Execution Desk',
    },
    accent: '#4D1A04',
    accentDark: '#3a1403',
    theme: {
      '--accent': '#4D1A04',
      '--ink': '#18181A',
      '--surface': '#F5F4EE',
      '--chrome-bg': '#18181A',
      '--chrome-text': '#F5F4EE',
    },
    supportCenter: 'Point72 Support',
    supportCenterSub: 'Trading Operations & Incident Intake',
    disclaimer: 'NOT ACTUALLY A POINT72 SITE — internal demo only, not affiliated with, endorsed by, or a real Point72 product.',
  },
  '704831b7': {
    slug: '704831b7',
    company: 'Hippocratic AI',
    brandMark: 'H',
    vertical: 'hightech',
    page: {
      // Natively branded custom page: served instead of the vertical's stock
      // page; the brand shim skips the title/logo rewrite for it.
      file: '704831b7.html',
      title: 'Hippocratic AI — Agent Deployment Console',
    },
    accent: '#15CC44',
    accentDark: '#10a838',
    theme: {
      '--accent': '#15CC44',
      '--ink': '#10163A',
      '--surface': '#ffffff',
      '--chrome-bg': '#0E2FAE',
      '--chrome-text': '#f2f6ff',
    },
    supportCenter: 'Hippocratic AI Support',
    supportCenterSub: 'Deployment Support & Incident Intake',
    disclaimer: 'NOT ACTUALLY A HIPPOCRATIC AI SITE — internal demo only, not affiliated with, endorsed by, or a real Hippocratic AI product.',
    bugPortal: {
      products: [
        {
          area: 'hightech',
          label: 'Agent Deployment Console \u2014 Campaign Provisioning',
          persona: { name: 'Priya Raghavan', email: 'priya.raghavan@brightmail.io', sev: 'High' },
          templates: [
            {
              id: 'hightech-provision-slowdown',
              label: 'Campaign provisioning noticeably slow',
              sev: 'Medium',
              text: 'Our deployment team flagged that provisioning a new outreach campaign in the console is painfully slow \u2014 every request sits for seven or eight seconds before completing. Nothing fails, it just crawls, and it seems to get a little worse with every campaign we provision.',
            },
            {
              id: 'hightech-renewal-slow',
              label: 'Cohort expansion crawling before go-live',
              sev: 'High',
              text: 'Clinical ops here \u2014 our health system goes live Monday and we are expanding the chronic care cohort by a couple hundred patients. Every provisioning call in the console sits there for ages before completing. The program director is on our call asking if the platform is falling over.',
            },
          ],
        },
      ],
    },
  },
  '2ab8a463': {
    slug: '2ab8a463',
    company: 'You.com',
    brandMark: 'Y',
    vertical: 'hightech',
    page: {
      // Natively branded custom page: served instead of the vertical's stock
      // page; the brand shim skips the title/logo rewrite for it.
      file: '2ab8a463.html',
      title: 'You.com — API Platform',
    },
    accent: '#5368EE',
    accentDark: '#3f53d8',
    theme: {
      '--accent': '#5368EE',
      '--ink': '#121212',
      '--surface': '#ffffff',
      '--chrome-bg': '#222B5F',
      '--chrome-text': '#ffffff',
    },
    supportCenter: 'You.com Support',
    supportCenterSub: 'Developer Support & Incident Intake',
    disclaimer: 'NOT ACTUALLY A YOU.COM SITE — internal demo only, not affiliated with, endorsed by, or a real You.com product.',
    bugPortal: {
      products: [
        {
          area: 'hightech',
          label: 'API Platform \u2014 Capacity Provisioning',
          persona: { name: 'Devon Ashcroft', email: 'devon.ashcroft@brightmail.io', sev: 'High' },
          templates: [
            {
              id: 'hightech-provision-slowdown',
              label: 'Provisioning capacity is slow',
              sev: 'Medium',
              text: 'Provisioning rate-limit capacity in the API Platform is crawling \u2014 every request sits for seven or eight seconds before the key comes back. Nothing errors, and it seems to get a bit worse with each endpoint we provision.',
            },
            {
              id: 'hightech-renewal-slow',
              label: 'Bulk key provisioning stalling before launch',
              sev: 'High',
              text: 'Platform team here \u2014 we ship our agent to production Monday and are provisioning keys and QPS for four endpoints across two regions. Every provisioning call in the console hangs for ages before it completes, so the whole rollout is behind. Our launch reviewer is asking whether the platform is healthy.',
            },
          ],
        },
      ],
    },
  },
  'e7c9dc7a': {
    slug: 'e7c9dc7a',
    company: 'DoorDash',
    brandMark: 'D',
    vertical: 'banking',
    page: {
      // Natively branded custom page: served instead of the vertical's stock
      // page; the brand shim skips the title/logo rewrite for it.
      file: 'e7c9dc7a.html',
      title: 'DoorDash — Dasher Earnings',
    },
    accent: '#EB1700',
    accentDark: '#c41300',
    theme: {
      '--accent': '#EB1700',
      '--ink': '#191919',
      '--surface': '#ffffff',
      '--chrome-bg': '#4C0C3A',
      '--chrome-text': '#ffffff',
    },
    supportCenter: 'DoorDash Support',
    supportCenterSub: 'Dasher Support & Incident Intake',
    disclaimer: 'NOT ACTUALLY A DOORDASH SITE — internal demo only, not affiliated with, endorsed by, or a real DoorDash product.',
    incident: {
      kind: 'banking-transfers',
      chatter: {
        vocabulary: {
          'enterprise customers': 'high-volume Dashers',
          'the payments gateway': 'the payout processor',
          'settlement timeouts': 'payout settlement timeouts',
          'Gateway team': 'Payout processor team',
          // Keep this repo-truthful code-path wording shielded from the broader transfer keys.
          'transfer path': 'transfer path',
          'the gateway': 'the payout processor',
          'Fund transfers degraded': 'Fast Pay cash outs degraded',
          'Transfers': 'Fast Pay cash outs',
          'transfers': 'Fast Pay cash outs',
          'transfer': 'Fast Pay cash out',
          'customers': 'Dashers',
        },
      },
    },
    bugPortal: {
      products: [
        {
          area: 'banking',
          label: 'Dasher Earnings \u2014 Fast Pay',
          persona: { name: 'Alex Rivera', email: 'alex.rivera@brightmail.io', sev: 'High' },
          templates: [
            {
              id: 'banking-transfer-slow',
              label: 'Fast Pay cash outs stuck on a spinner',
              sev: 'High',
              text: 'Cashing out my earnings used to be quick, but now every cash out sits on a spinner for about ten seconds before it goes through. Tried different amounts and both my bank account and my DasherDirect card \u2014 same thing every time. Started today.',
            },
            {
              id: 'banking-payroll-cutoff',
              label: 'End-of-shift payouts running late',
              sev: 'Critical',
              text: 'Escalating on behalf of a market team: Dashers cashing out at the end of the dinner shift are queued one after another and each cash out now takes ~10 seconds, so the whole batch finishes well after the usual window. Nothing errors \u2014 it is just painfully slow, and it was fine yesterday.',
            },
          ],
        },
      ],
    },
  },
  '81fea074': {
    slug: '81fea074',
    company: 'Stellic',
    brandMark: 'S',
    vertical: 'hightech',
    page: {
      // Natively branded custom page: served instead of the vertical's stock
      // page; the brand shim skips the title/logo rewrite for it.
      file: '81fea074.html',
      title: 'Stellic — Registration',
    },
    accent: '#C1441A',
    accentDark: '#a53a15',
    theme: {
      '--accent': '#C1441A',
      '--ink': '#151B26',
      '--surface': '#ffffff',
      '--chrome-bg': '#151B26',
      '--chrome-text': '#F5F4ED',
    },
    supportCenter: 'Stellic Support',
    supportCenterSub: 'Institution Support & Incident Intake',
    disclaimer: 'NOT ACTUALLY A STELLIC SITE — internal demo only, not affiliated with, endorsed by, or a real Stellic product.',
  },
  '08d969be': {
    slug: '08d969be',
    company: 'Hadrian',
    brandMark: 'H',
    vertical: 'industrials',
    page: {
      file: '08d969be.html',
      title: 'Hadrian — Instant Quote',
    },
    accent: '#12325C',
    accentDark: '#0d2544',
    theme: {
      '--accent': '#12325C',
      '--ink': '#101820',
      '--surface': '#ffffff',
      '--chrome-bg': '#0A1626',
      '--chrome-text': '#ffffff',
    },
    supportCenter: 'Hadrian Support',
    supportCenterSub: 'Customer Care & Incident Intake',
    disclaimer: 'NOT ACTUALLY A HADRIAN SITE — internal demo only, not affiliated with, endorsed by, or a real Hadrian product.',
    bugPortal: {
      products: [
        {
          area: 'industrials',
          label: 'Hadrian Instant Quote — DFM Analysis',
          persona: { name: 'Morgan Reyes', email: 'morgan.reyes@brightmail.io', sev: 'High' },
          templates: [
            {
              id: 'industrials-quote-timeout',
              label: 'Instant quote taking too long',
              sev: 'High',
              text: 'Buyer at a defense prime here — our instant quote sits on “Running DFM analysis” for about 15 seconds before it finally returns. Same part and quantity every time, and this started recently.',
            },
            {
              id: 'industrials-program-quotes-blocked',
              label: 'Program quotes crawling',
              sev: 'Critical',
              text: 'Program manager escalation: every quote for one aerospace program crawls while quotes for other programs come back in about a second. We need the affected program quotes for today’s sourcing review.',
            },
          ],
        },
      ],
    },
  },
  'cdf0771d': {
    slug: 'cdf0771d',
    company: 'RadixArk',
    brandMark: 'R',
    vertical: 'inference',
    page: {
      // Natively branded custom page: served instead of the vertical's stock
      // page; the brand shim skips the title/logo rewrite for it.
      file: 'cdf0771d.html',
      title: 'RadixArk — Serving Console',
    },
    theme: {
      '--accent': '#D55816',
      '--ink': '#1A1512',
      '--surface': '#FBF7F2',
      '--chrome-bg': '#0C0B0A',
      '--chrome-text': '#F8F2EA',
    },
    supportCenter: 'RadixArk Support',
    supportCenterSub: 'Platform Support & Incident Intake',
    disclaimer: 'NOT ACTUALLY A RADIXARK SITE — internal demo only, not affiliated with, endorsed by, or a real RadixArk product.',
  },
  '2acc11fd': {
    slug: '2acc11fd',
    company: 'Wispr Flow',
    brandMark: 'F',
    vertical: 'voice',
    page: {
      // Natively branded custom page: served instead of the vertical's stock
      // page; the brand shim skips the title/logo rewrite for it.
      file: '2acc11fd.html',
      title: 'Wispr Flow — Dictation',
    },
    theme: {
      '--accent': '#1A1A1A',
      '--ink': '#1A1A1A',
      '--surface': '#FFFFEB',
      '--chrome-bg': '#1F1F1F',
      '--chrome-text': '#FFFFEB',
    },
    supportCenter: 'Wispr Flow Support',
    supportCenterSub: 'Workspace Support & Incident Intake',
    disclaimer: 'NOT ACTUALLY A WISPR FLOW SITE — internal demo only, not affiliated with, endorsed by, or a real Wispr Flow product.',
  },
  '3aea27ba': {
    slug: '3aea27ba',
    company: 'Happen Bank',
    brandMark: 'H',
    vertical: 'banking',
    page: {
      // Natively branded custom page: served instead of the vertical's stock
      // page; the brand shim skips the title/logo rewrite for it.
      file: '3aea27ba.html',
      title: 'Happen Bank — Move Money',
    },
    accent: '#2626FF',
    accentDark: '#1E1FCA',
    theme: {
      '--accent': '#2626FF',
      '--ink': '#232222',
      '--surface': '#fffdfb',
      '--chrome-bg': '#232222',
      '--chrome-text': '#F7F1ED',
    },
    supportCenter: 'Happen Bank Support',
    supportCenterSub: 'Customer Care & Incident Intake',
    disclaimer: 'NOT ACTUALLY A HAPPEN BANK SITE — internal demo only, not affiliated with, endorsed by, or a real Happen Bank product.',
  },
  '32715aba': {
    slug: '32715aba',
    company: 'Mercor',
    brandMark: 'M',
    vertical: 'banking',
    page: {
      // Natively branded custom page: served instead of the vertical's stock
      // page, so the brand shim skips the title/logo rewrite. Keep the file's
      // own <title> in sync with page.title.
      file: '32715aba.html',
      title: 'Mercor \u2014 Earnings',
    },
    accent: '#4F46E5',
    accentDark: '#4338CA',
    theme: {
      '--accent': '#4F46E5',
      '--ink': '#0b0b0f',
      '--surface': '#ffffff',
      '--chrome-bg': '#111116',
      '--chrome-text': '#f5f5f7',
    },
    supportCenter: 'Mercor Support',
    supportCenterSub: 'Customer Care & Incident Intake',
    disclaimer: 'NOT ACTUALLY A MERCOR SITE — internal demo only, not affiliated with, endorsed by, or a real Mercor product.',
  },
  'e51b6dc0': {
    slug: 'e51b6dc0',
    company: 'Crisil',
    brandMark: 'C',
    vertical: 'banking',
    page: {
      // Natively branded custom page: served instead of the vertical's stock
      // page, so the brand shim skips the title/logo rewrite. Keep the file's
      // own <title> in sync with page.title.
      file: 'e51b6dc0.html',
      title: 'Crisil Integral IQ \u2014 Credit Risk Run',
    },
    accent: '#E8622A',
    accentDark: '#C94F1D',
    theme: {
      '--accent': '#E8622A',
      '--ink': '#14213D',
      '--surface': '#ffffff',
      '--chrome-bg': '#06183A',
      '--chrome-text': '#EAF1FB',
    },
    devinSession: { auto: true },
    supportCenter: 'Crisil Client Support',
    supportCenterSub: 'Analytics Platform Care & Incident Intake',
    disclaimer: 'NOT ACTUALLY A CRISIL SITE — internal demo only, not affiliated with, endorsed by, or a real Crisil product.',
    bugPortal: {
      products: [
        {
          area: 'banking',
          label: 'Crisil Integral IQ \u2014 Credit Risk Runs',
          persona: { name: 'Ananya Rao', email: 'ananya.rao@northmeridiancap.in', sev: 'High' },
          templates: [
            {
              id: 'banking-transfer-slow',
              label: 'Scoring runs extremely slow',
              sev: 'High',
              text: 'Our credit team is telling us Integral IQ scoring runs take forever now. You submit a run and the button sits there for a good ten seconds before results come back. Any portfolio on the standard run tier, every time. It does complete, it is just painfully slow, and it started today.',
            },
            {
              id: 'banking-payroll-cutoff',
              label: 'Overnight risk batch missing the reporting cutoff',
              sev: 'Critical',
              text: 'Escalating from risk ops: our overnight batch submits scoring runs one after another and each one now takes ~10 seconds, so the batch will miss the regulatory reporting cutoff. Nothing errors — it is just slow, and it was fine on Friday. Please treat as urgent.',
            },
          ],
        },
      ],
    },
  },
  'a198d45f': {
    slug: 'a198d45f',
    company: 'MediCodio',
    brandMark: 'M',
    vertical: 'insurance',
    page: {
      file: 'a198d45f.html',
      title: 'MediCodio AI — CODIO Coding Workspace',
    },
    theme: {
      '--accent': '#00309F',
      '--ink': '#141834',
      '--surface': '#ffffff',
      '--chrome-bg': '#141834',
      '--chrome-text': '#F5F7FC',
    },
    supportCenter: 'MediCodio Support',
    supportCenterSub: 'Customer Care & Incident Intake',
    disclaimer: 'NOT ACTUALLY A MEDICODIO SITE — internal demo only, not affiliated with, endorsed by, or a real MediCodio product.',
  },

  '03848ffe': {
    slug: '03848ffe',
    company: 'Genspark',
    brandMark: 'G',
    vertical: 'hightech',
    page: {
      file: '03848ffe.html',
      title: 'Genspark - Upgrade to Team Plan',
    },
    theme: {
      '--accent': '#0F7FFF',
      '--ink': '#232425',
      '--surface': '#ffffff',
      '--chrome-bg': '#000000',
      '--chrome-text': '#ffffff',
    },
    supportCenter: 'Genspark Support',
    supportCenterSub: 'Customer Care & Incident Intake',
    disclaimer: 'NOT ACTUALLY A GENSPARK SITE — internal demo only, not affiliated with, endorsed by, or a real Genspark product.',
    bugPortal: {
      products: [
        {
          area: 'hightech',
          label: 'AI Workspace \u2014 Team Seats & Provisioning',
          persona: { name: 'Elena Sorokin', email: 'elena.sorokin@northloop.io', sev: 'Medium' },
          templates: [
            {
              id: 'hightech-provision-slowdown',
              label: 'Adding seats is very slow',
              sev: 'Medium',
              text: 'Adding seats to our Team plan is painfully slow — every time I hit "Get Team seats" it sits for seven or eight seconds before the workspace updates. It does go through, it is just slow, and it feels a little worse each time we add another batch.',
            },
            {
              id: 'hightech-renewal-slow',
              label: 'Bulk seat expansion crawling before renewal',
              sev: 'High',
              text: 'We are expanding from 40 to 200 seats ahead of our renewal on Friday and every seat batch in the workspace admin sits there for ages before it completes. Our IT lead is convinced the platform cannot handle our org size.',
            },
          ],
        },
      ],
    },
  },
  'ec8c777e': {
    slug: 'ec8c777e',
    company: 'Shinhan Bank',
    brandMark: 'S',
    vertical: 'banking',
    page: {
      file: 'ec8c777e.html',
      title: '계좌이체 | 신한은행 개인뱅킹',
    },
    theme: {
      '--accent': '#2D71C4',
      '--ink': '#343434',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#1F4E86',
      '--chrome-text': '#FFFFFF',
    },
    supportCenter: '신한은행 고객센터',
    disclaimer: 'NOT ACTUALLY A SHINHAN BANK SITE — internal demo only, not affiliated with, endorsed by, or a real Shinhan Bank product.',
  },
  '000e17f3': {
    slug: '000e17f3',
    company: '우리은행',
    brandMark: 'W',
    vertical: 'banking',
    page: {
      file: '000e17f3.html',
      title: '계좌이체 | 우리은행 개인뱅킹',
    },
    theme: {
      '--accent': '#0083cd',
      '--ink': '#222222',
      '--surface': '#ffffff',
      '--chrome-bg': '#0661c4',
      '--chrome-text': '#ffffff',
    },
    supportCenter: '우리은행 고객센터',
    disclaimer: 'NOT ACTUALLY A WOORI BANK SITE — internal demo only, not affiliated with, endorsed by, or a real Woori Bank product.',
  },
  '63840dfd': {
    slug: '63840dfd',
    company: 'Chapter',
    brandMark: 'C',
    vertical: 'telco',
    page: {
      file: '63840dfd.html',
      title: 'Change Your Medicare Plan with a Licensed Advisor | Chapter',
    },
    theme: {
      '--accent': '#FD2F4C',
      '--ink': '#000000',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#180D43',
      '--chrome-text': '#FDF5EE',
    },
    supportCenter: 'Chapter Support',
    disclaimer: 'NOT ACTUALLY A CHAPTER SITE — internal demo only, not affiliated with, endorsed by, or a real Chapter product.',
  },
  'd5f6d175': {
    slug: 'd5f6d175',
    company: 'Shinsegae',
    brandMark: 'S',
    vertical: 'telco',
    page: {
      file: 'd5f6d175.html',
      title: '신세계 유니버스 클럽 멤버십 관리 | 신세계포인트',
    },
    theme: {
      '--accent': '#A3833F',
      '--ink': '#222222',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#05071A',
      '--chrome-text': '#FFFFFF',
    },
    supportCenter: '신세계포인트 고객센터',
    disclaimer: 'NOT ACTUALLY A SHINSEGAE SITE — internal demo only, not affiliated with, endorsed by, or a real Shinsegae product.',
  },
  'c65bd444': {
    slug: 'c65bd444',
    company: 'Korean Air',
    brandMark: 'K',
    vertical: 'banking',
    page: {
      file: 'c65bd444.html',
      title: '스카이패스 마일리지 양도/합산 | 대한항공',
    },
    theme: {
      '--accent': '#051766',
      '--ink': '#1a1a1a',
      '--surface': '#ffffff',
      '--chrome-bg': '#051766',
      '--chrome-text': '#f2f7ff',
    },
    supportCenter: 'Korean Air Support',
    supportCenterSub: 'SKYPASS Member Care',
    disclaimer: 'NOT ACTUALLY A KOREAN AIR SITE — internal demo only, not affiliated with, endorsed by, or a real Korean Air product.',
  },
  'bcda19cc': {
    slug: 'bcda19cc',
    company: 'Hyundai',
    brandMark: 'H',
    vertical: 'telco',
    page: {
      file: 'bcda19cc.html',
      title: '블루링크 구독 관리 | 현대자동차',
    },
    theme: {
      '--accent': '#002C5F',
      '--ink': '#1B1B1B',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#001C3D',
      '--chrome-text': '#FFFFFF',
    },
    supportCenter: '현대자동차 고객센터',
    disclaimer: 'NOT ACTUALLY A HYUNDAI SITE — internal demo only, not affiliated with, endorsed by, or a real Hyundai product.',
  },
  '4f8523aa': {
    slug: '4f8523aa',
    company: 'Kakao Pay',
    brandMark: 'K',
    vertical: 'banking',
    page: {
      file: '4f8523aa.html',
      title: '카카오페이 | 결제',
    },
    theme: {
      '--accent': '#FFEB00',
      '--ink': '#060B11',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#191C20',
      '--chrome-text': '#FFFFFF',
    },
    supportCenter: 'Kakao Pay Support',
    disclaimer: 'NOT ACTUALLY A KAKAO PAY SITE — internal demo only, not affiliated with, endorsed by, or a real Kakao Pay product.',
  },
  '1ac469b4': {
    slug: '1ac469b4',
    company: '정부24',
    brandMark: 'G',
    vertical: 'banking',
    page: {
      file: '1ac469b4.html',
      title: '증명서 발급 수수료 결제 | 정부24',
    },
    theme: {
      '--accent': '#256ef4',
      '--ink': '#1e2124',
      '--surface': '#ffffff',
      '--chrome-bg': '#052b57',
      '--chrome-text': '#ffffff',
    },
    supportCenter: '정부24 고객센터',
    disclaimer: 'NOT ACTUALLY A GOV.KR (정부24) SITE — internal demo only, not affiliated with, endorsed by, or a real Government of Korea service.',
  },
  'bf5f21e3': {
    slug: 'bf5f21e3',
    company: 'Forrester',
    brandMark: 'F',
    vertical: 'hightech',
    page: {
      file: 'bf5f21e3.html',
      title: 'Forrester Decisions | Manage Seats',
    },
    theme: {
      '--accent': '#10398C',
      '--ink': '#1F2733',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#000000',
      '--chrome-text': '#FFFFFF',
    },
    supportCenter: 'Forrester Client Support',
    disclaimer: 'NOT ACTUALLY A FORRESTER SITE — internal demo only, not affiliated with, endorsed by, or a real Forrester product.',
  },
  '0c15262a': {
    slug: '0c15262a',
    company: '하나은행',
    brandMark: 'H',
    vertical: 'banking',
    page: {
      file: '0c15262a.html',
      title: '계좌이체 | 하나은행',
    },
    theme: {
      '--accent': '#009591',
      '--ink': '#191919',
      '--surface': '#ffffff',
      '--chrome-bg': '#00605e',
      '--chrome-text': '#ffffff',
    },
    supportCenter: '하나은행 고객센터',
    disclaimer: 'NOT ACTUALLY A HANA BANK (하나은행) SITE — internal demo only, not affiliated with, endorsed by, or a real Hana Bank product.',
  },
  '5d5755c2': {
    slug: '5d5755c2',
    company: 'MegazoneCloud',
    brandMark: 'M',
    vertical: 'hightech',
    page: {
      file: '5d5755c2.html',
      title: '라이선스 프로비저닝 | MegazoneCloud',
    },
    theme: {
      '--accent': '#6C4CF1',
      '--ink': '#191919',
      '--surface': '#ffffff',
      '--chrome-bg': '#0A0F10',
      '--chrome-text': '#ffffff',
    },
    supportCenter: 'MegazoneCloud 고객지원',
    disclaimer: 'NOT ACTUALLY A MEGAZONECLOUD SITE — internal demo only, not affiliated with, endorsed by, or a real MegazoneCloud product.',
  },
  'f5a5bdad': {
    slug: 'f5a5bdad',
    company: 'KRAFTON',
    brandMark: 'K',
    vertical: 'banking',
    page: {
      file: 'f5a5bdad.html',
      title: 'G-COIN 충전 | KRAFTON',
    },
    theme: {
      '--accent': '#F73A31',
      '--ink': '#191919',
      '--surface': '#ffffff',
      '--chrome-bg': '#000000',
      '--chrome-text': '#ffffff',
    },
    supportCenter: 'KRAFTON 고객지원',
    disclaimer: 'NOT ACTUALLY A KRAFTON SITE — internal demo only, not affiliated with, endorsed by, or a real KRAFTON product.',
  },
  'd92336aa': {
    slug: 'd92336aa',
    company: '카카오톡 선물하기',
    brandMark: 'K',
    vertical: 'banking',
    page: {
      file: 'd92336aa.html',
      title: '선물 결제 | 카카오톡 선물하기',
    },
    theme: {
      '--accent': '#F6432F',
      '--ink': '#191919',
      '--surface': '#ffffff',
      '--chrome-bg': '#191919',
      '--chrome-text': '#ffffff',
    },
    supportCenter: '카카오 고객센터',
    disclaimer: 'NOT ACTUALLY A KAKAO SITE — internal demo only, not affiliated with, endorsed by, or a real Kakao product.',
  },
  'c70eca54': {
    slug: 'c70eca54',
    company: '삼성카드',
    brandMark: 'S',
    vertical: 'banking',
    page: {
      file: 'c70eca54.html',
      title: '카드대금 즉시결제 | 삼성카드',
    },
    theme: {
      '--accent': '#2090FF',
      '--ink': '#111111',
      '--surface': '#ffffff',
      '--chrome-bg': '#101010',
      '--chrome-text': '#ffffff',
    },
    supportCenter: '삼성카드 고객센터',
    disclaimer: 'NOT ACTUALLY A SAMSUNG CARD SITE — internal demo only, not affiliated with, endorsed by, or a real Samsung Card product.',
  },
  '9f7a8436': {
    slug: '9f7a8436',
    company: 'Mercedes-Benz',
    brandMark: 'M',
    vertical: 'telco',
    page: {
      file: '9f7a8436.html',
      title: 'Mercedes me connect — Digital Extras',
    },
    theme: {
      '--accent': '#0078D6',
      '--ink': '#141414',
      '--surface': '#ffffff',
      '--chrome-bg': '#000000',
      '--chrome-text': '#ffffff',
    },
    supportCenter: 'Mercedes-Benz Customer Assistance',
    disclaimer: 'NOT ACTUALLY A MERCEDES-BENZ SITE — internal demo only, not affiliated with, endorsed by, or a real Mercedes-Benz product.',
  },
  'd22a0a30': {
    slug: 'd22a0a30',
    company: 'Pearson',
    brandMark: 'P',
    vertical: 'telco',
    page: { file: 'd22a0a30.html', title: 'Pearson+ | Manage subscription' },
    theme: {
      '--accent': '#6D0176',
      '--ink': '#333333',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#05112A',
      '--chrome-text': '#FFFFFF',
    },
    supportCenter: 'Pearson Support',
    disclaimer: 'NOT ACTUALLY A PEARSON SITE — internal demo only, not affiliated with, endorsed by, or a real Pearson product.',
  },
  '93f1b8ec': {
    slug: '93f1b8ec',
    company: 'הראל',
    brandMark: 'ה',
    vertical: 'insurance',
    page: { file: '93f1b8ec.html', title: 'הגשת תביעה | הראל ביטוח ופיננסים' },
    theme: {
      '--accent': '#106AE1',
      '--ink': '#1F1F1F',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#1F1F1F',
      '--chrome-text': '#FFFFFF',
    },
    supportCenter: 'הראל שירות לקוחות',
    disclaimer: 'NOT ACTUALLY A HAREL SITE — internal demo only, not affiliated with, endorsed by, or a real Harel Insurance product.',
  },
  'd61e15a2': {
    slug: 'd61e15a2',
    company: 'BMW',
    brandMark: 'B',
    vertical: 'banking',
    page: { file: 'd61e15a2.html', title: 'Reserve your BMW | BMW Shop Online' },
    theme: {
      '--accent': '#1C69D4',
      '--ink': '#262626',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#262626',
      '--chrome-text': '#FFFFFF',
    },
    supportCenter: 'BMW Customer Support',
    disclaimer: 'NOT ACTUALLY A BMW SITE — internal demo only, not affiliated with, endorsed by, or a real BMW product.',
  },
  'b258a21e': {
    slug: 'b258a21e',
    company: 'Telekom',
    brandMark: 'T',
    vertical: 'telco',
    page: { file: 'b258a21e.html', title: 'Tarifwechsel | Telekom' },
    theme: {
      '--accent': '#E20074',
      '--ink': '#262626',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#262626',
      '--chrome-text': '#FFFFFF',
    },
    supportCenter: 'Telekom Kundenservice',
    disclaimer: 'NOT ACTUALLY A DEUTSCHE TELEKOM SITE — internal demo only, not affiliated with, endorsed by, or a real Deutsche Telekom product.',
  },
  'dec00361': {
    slug: 'dec00361',
    company: 'T-Systems',
    brandMark: 'T',
    vertical: 'hightech',
    page: { file: 'dec00361.html', title: 'Provision Licenses | T-Systems Cloud Services' },
    theme: {
      '--accent': '#E20074',
      '--ink': '#262626',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#000000',
      '--chrome-text': '#FFFFFF',
    },
    supportCenter: 'T-Systems Service Desk',
    disclaimer: 'NOT ACTUALLY A T-SYSTEMS SITE — internal demo only, not affiliated with, endorsed by, or a real T-Systems / Deutsche Telekom product.',
  },
  '1c4b185f': {
    slug: '1c4b185f',
    company: 'Stellantis Financial Services',
    brandMark: 'S',
    vertical: 'banking',
    page: { file: '1c4b185f.html', title: 'Make a payment | Stellantis Financial Services' },
    theme: {
      '--accent': '#243882',
      '--ink': '#212529',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#282B34',
      '--chrome-text': '#FFFFFF',
    },
    supportCenter: 'Stellantis Financial Services Customer Care',
    disclaimer: 'NOT ACTUALLY A STELLANTIS SITE — internal demo only, not affiliated with, endorsed by, or a real Stellantis product.',
  },
  '02238eb0': {
    slug: '02238eb0',
    company: 'Harborline FCU',
    brandMark: 'H',
    vertical: 'banking',
    page: { file: '02238eb0.html', title: 'Transfer money | Harborline FCU Digital Banking' },
    theme: {
      '--accent': '#123a6b',
      '--ink': '#1b2230',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#0b1f3a',
      '--chrome-text': '#FFFFFF',
    },
    supportCenter: 'Harborline FCU Member Services',
    supportCenterSub: 'Digital Banking Support',
    disclaimer: 'Harborline FCU is a fictional credit union — internal demo only, not affiliated with any real financial institution.',
  },
  'ae0823ea': {
    slug: 'ae0823ea',
    company: 'Raymond James',
    brandMark: 'RJ',
    vertical: 'banking',
    page: { file: 'ae0823ea.html', title: 'Transfer Funds | Client Access | Raymond James' },
    theme: {
      '--accent': '#002949',
      '--ink': '#000000',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#002949',
      '--chrome-text': '#FFFFFF',
    },
    supportCenter: 'Client Access Support',
    disclaimer: 'NOT ACTUALLY A RAYMOND JAMES SITE — internal demo only, not affiliated with, endorsed by, or a real Raymond James product.',
  },
  '3febe675': {
    slug: '3febe675',
    company: 'Amadeus',
    brandMark: 'a',
    vertical: 'hightech',
    page: { file: '3febe675.html', title: 'Amadeus Enterprise API Portal | Provision access' },
    theme: {
      '--accent': '#0C66E1',
      '--ink': '#333333',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#000835',
      '--chrome-text': '#FFFFFF',
    },
    supportCenter: 'Amadeus Developer Support',
    disclaimer: 'NOT ACTUALLY AN AMADEUS SITE — internal demo only, not affiliated with, endorsed by, or a real Amadeus product.',
  },
  'c789e3c0': {
    slug: 'c789e3c0',
    company: 'Nationale-Nederlanden',
    brandMark: 'N',
    vertical: 'insurance',
    page: { file: 'c789e3c0.html', title: 'Schade melden | Nationale-Nederlanden' },
    theme: {
      '--accent': '#EA650D',
      '--ink': '#404040',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#1A1A1A',
      '--chrome-text': '#FFFFFF',
    },
    supportCenter: 'NN Klantenservice',
    disclaimer: 'NOT ACTUALLY A NATIONALE-NEDERLANDEN (NN GROUP) SITE — internal demo only, not affiliated with, endorsed by, or a real NN product.',
  },
  'b3387c66': {
    slug: 'b3387c66',
    company: 'British Airways',
    brandMark: 'BA',
    vertical: 'banking',
    page: { file: 'b3387c66.html', title: 'Pay for your booking | British Airways' },
    theme: {
      '--accent': '#3468AD',
      '--ink': '#000000',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#01122C',
      '--chrome-text': '#FFFFFF',
    },
    supportCenter: 'British Airways Customer Relations',
    disclaimer: 'NOT ACTUALLY A BRITISH AIRWAYS SITE — internal demo only, not affiliated with, endorsed by, or a real British Airways product.',
  },
  'df86b36f': {
    slug: 'df86b36f',
    company: 'L&G',
    brandMark: 'L&G',
    vertical: 'banking',
    page: { file: 'df86b36f.html', title: 'Fund dealing | L&G Asset Management' },
    theme: {
      '--accent': '#005DBA',
      '--ink': '#1D1D1B',
      '--surface': '#ffffff',
      '--chrome-bg': '#002855',
      '--chrome-text': '#ffffff',
    },
    supportCenter: 'L&G Client Services',
    disclaimer: 'NOT ACTUALLY AN L&G SITE — internal demo only, not affiliated with, endorsed by, or a real L&G product.',
  },
  '290929de': {
    slug: '290929de',
    company: 'Bank Leumi',
    brandMark: 'L',
    vertical: 'banking',
    page: { file: '290929de.html', title: 'העברת כספים | לאומי דיגיטל' },
    theme: {
      '--accent': '#0066FF',
      '--ink': '#070762',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#10069A',
      '--chrome-text': '#FFFFFF',
    },
    supportCenter: 'Bank Leumi Customer Service',
    disclaimer: 'NOT ACTUALLY A BANK LEUMI SITE — internal demo only, not affiliated with, endorsed by, or a real Bank Leumi product.',
  },
  '2e94691c': {
    slug: '2e94691c',
    company: 'Wiz',
    brandMark: 'W',
    vertical: 'hightech',
    page: { file: '2e94691c.html', title: 'Wiz — Cloud Connector Deployment' },
    accent: '#0254EC',
    accentDark: '#0143C0',
    theme: {
      '--accent': '#0254EC',
      '--ink': '#393F49',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#25242F',
      '--chrome-text': '#F4F4F6',
    },
    supportCenter: 'Wiz Support',
    supportCenterSub: 'Deployment Support & Incident Intake',
    disclaimer: 'NOT ACTUALLY A WIZ SITE — internal demo only, not affiliated with, endorsed by, or a real Wiz product.',
  },
  'abb0d034': {
    slug: 'abb0d034',
    company: 'Monte Carlo',
    brandMark: 'MC',
    vertical: 'hightech',
    page: {
      file: 'abb0d034.html',
      title: 'Monte Carlo | Monitors',
    },
    theme: {
      '--accent': '#FF5700',
      '--ink': '#00111D',
      '--surface': '#ffffff',
      '--chrome-bg': '#00111D',
      '--chrome-text': '#ffffff',
    },
    supportCenter: 'Monte Carlo Support',
    supportCenterSub: 'Customer Care & Incident Intake',
    disclaimer: 'NOT ACTUALLY A MONTE CARLO SITE — internal demo only, not affiliated with, endorsed by, or a real Monte Carlo product.',
  },
  'c84ab9c6': {
    slug: 'c84ab9c6',
    company: 'Luma',
    brandMark: 'L',
    vertical: 'hightech',
    page: { file: 'c84ab9c6.html', title: 'Add dedicated capacity | Luma API' },
    accent: '#202020',
    accentDark: '#000000',
    theme: {
      '--accent': '#202020',
      '--ink': '#202020',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#050607',
      '--chrome-text': '#F1F1F1',
    },
    supportCenter: 'Luma Support',
    supportCenterSub: 'API Capacity & Platform Support',
    disclaimer: 'NOT ACTUALLY A LUMA SITE — internal demo only, not affiliated with, endorsed by, or a real Luma product.',
  },
  'a46b7c5e': {
    slug: 'a46b7c5e',
    company: 'Erste Bank',
    brandMark: 'E',
    vertical: 'banking',
    page: {
      file: 'a46b7c5e.html',
      title: 'Send money | George – Erste Bank',
    },
    theme: {
      '--accent': '#2870ED',
      '--ink': '#303030',
      '--surface': '#ffffff',
      '--chrome-bg': '#0B1F42',
      '--chrome-text': '#ffffff',
    },
    supportCenter: 'Erste Bank Customer Service',
    disclaimer: 'NOT ACTUALLY AN ERSTE BANK SITE — internal demo only, not affiliated with, endorsed by, or a real Erste Group product.',
  },
  '4a3e91b9': {
    slug: '4a3e91b9',
    company: 'Hargreaves Lansdown',
    brandMark: 'HL',
    vertical: 'banking',
    page: {
      file: '4a3e91b9.html',
      title: 'Add money | Stocks and Shares ISA – Hargreaves Lansdown',
    },
    theme: {
      '--accent': '#0A70DC',
      '--ink': '#1A1A1A',
      '--surface': '#ffffff',
      '--chrome-bg': '#071D49',
      '--chrome-text': '#ffffff',
    },
    supportCenter: 'Hargreaves Lansdown Helpdesk',
    disclaimer: 'NOT ACTUALLY A HARGREAVES LANSDOWN SITE — internal demo only, not affiliated with, endorsed by, or a real Hargreaves Lansdown product.',
  },
  '7da5a0a9': {
    slug: '7da5a0a9',
    company: 'AECOM',
    brandMark: 'A',
    vertical: 'hightech',
    page: {
      // Natively branded custom page: served instead of the vertical's stock
      // page; the brand shim skips the title/logo rewrite for it.
      file: '7da5a0a9.html',
      title: 'plan.engage — Project team access | Digital AECOM',
    },
    accent: '#008768',
    accentDark: '#016b54',
    theme: {
      '--accent': '#008768',
      '--ink': '#000000',
      '--surface': '#ffffff',
      '--chrome-bg': '#000000',
      '--chrome-text': '#ffffff',
    },
    supportCenter: 'Digital AECOM Support',
    disclaimer: 'NOT ACTUALLY AN AECOM SITE — internal demo only, not affiliated with, endorsed by, or a real AECOM product.',
  },
  '232108b7': {
    slug: '232108b7',
    company: 'Prudential',
    brandMark: 'P',
    vertical: 'insurance',
    page: { file: '232108b7.html', title: 'Make a claim | Prudential' },
    theme: {
      '--accent': '#DA291C',
      '--ink': '#1C1D1B',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#1C1D1B',
      '--chrome-text': '#FFFFFF',
    },
    supportCenter: 'Prudential Customer Service',
    disclaimer: 'NOT ACTUALLY A PRUDENTIAL SITE — internal demo only, not affiliated with, endorsed by, or a real Prudential plc product.',
  },
  '7abf90ac': {
    slug: '7abf90ac',
    company: 'Coursera',
    brandMark: 'C',
    vertical: 'telco',
    page: { file: '7abf90ac.html', title: 'Coursera Plus | Manage your subscription' },
    accent: '#0056D2',
    accentDark: '#00419e',
    theme: {
      '--accent': '#0056D2',
      '--ink': '#1F1F1F',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#001129',
      '--chrome-text': '#FFFFFF',
    },
    supportCenter: 'Coursera Learner Help Center',
    disclaimer: 'NOT ACTUALLY A COURSERA SITE — internal demo only, not affiliated with, endorsed by, or a real Coursera product.',
  },
  'f9767587': {
    slug: 'f9767587',
    company: '1-800-Flowers.com',
    brandMark: 'F',
    vertical: 'telco',
    page: { file: 'f9767587.html', title: 'Celebrations Passport® | Manage Membership - 1-800-Flowers.com' },
    accent: '#201648',
    accentDark: '#150e33',
    theme: {
      '--accent': '#201648',
      '--ink': '#2f2f2f',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#201648',
      '--chrome-text': '#FAFAFA',
    },
    supportCenter: '1-800-Flowers.com Customer Service',
    disclaimer: 'NOT ACTUALLY A 1-800-FLOWERS.COM SITE — internal demo only, not affiliated with, endorsed by, or a real 1-800-Flowers.com product.',
  },
  'd9d2f2fd': {
    slug: 'd9d2f2fd',
    company: 'Lloyds Bank',
    brandMark: 'LLOYDS',
    vertical: 'banking',
    page: {
      file: 'd9d2f2fd.html',
      title: 'Pay & transfer | Internet Banking – Lloyds Bank',
    },
    theme: {
      '--accent': '#11B67A',
      '--ink': '#000000',
      '--surface': '#ffffff',
      '--chrome-bg': '#006A4D',
      '--chrome-text': '#ffffff',
    },
    supportCenter: 'Lloyds Bank Help & Support',
    disclaimer: 'NOT ACTUALLY A LLOYDS BANK SITE — internal demo only, not affiliated with, endorsed by, or a real Lloyds Bank product.',
  },
  'f2089246': {
    slug: 'f2089246',
    company: 'Function Health',
    brandMark: 'F',
    vertical: 'hightech',
    page: {
      // Natively branded custom page: served instead of the vertical's stock
      // page; the brand shim skips the title/logo rewrite for it.
      file: 'f2089246.html',
      title: 'Function — Member Dashboard',
    },
    accent: '#B05A36',
    accentDark: '#8f4729',
    theme: {
      '--accent': '#B05A36',
      '--ink': '#2A2B2F',
      '--surface': '#FEF9EF',
      '--chrome-bg': '#2A2B2F',
      '--chrome-text': '#FEF9EF',
    },
    supportCenter: 'Function Support',
    supportCenterSub: 'Member Care & Incident Intake',
    disclaimer: 'NOT ACTUALLY A FUNCTION HEALTH SITE — internal demo only, not affiliated with, endorsed by, or a real Function Health product.',
  },
  '1dd18f07': {
    slug: '1dd18f07',
    company: 'Eaze',
    brandMark: 'E',
    vertical: 'banking',
    page: {
      file: '1dd18f07.html',
      title: 'Checkout | Eaze',
    },
    theme: {
      '--accent': '#FFE400',
      '--ink': '#000000',
      '--surface': '#ffffff',
      '--chrome-bg': '#000000',
      '--chrome-text': '#ffffff',
    },
    supportCenter: 'Eaze Support',
    disclaimer: 'NOT ACTUALLY A EAZE SITE — internal demo only, not affiliated with, endorsed by, or a real Eaze product.',
  },
  '97d17d45': {
    slug: '97d17d45',
    company: 'Parallel',
    brandMark: 'P',
    vertical: 'hightech',
    page: {
      file: '97d17d45.html',
      title: 'Provision seats | Parallel Platform',
    },
    theme: {
      '--accent': '#FB631B',
      '--ink': '#181818',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#202020',
      '--chrome-text': '#FFFFFF',
    },
    devinSession: { auto: true },
    supportCenter: 'Parallel Support',
    disclaimer: 'NOT ACTUALLY A PARALLEL SITE — internal demo only, not affiliated with, endorsed by, or a real Parallel Web Systems product.',
  },
  'b96d078d': {
    slug: 'b96d078d',
    company: 'Bloomberg Law',
    brandMark: 'BL',
    vertical: 'hightech',
    page: { file: 'b96d078d.html', title: 'Add users | Firm Administration – Bloomberg Law' },
    theme: {
      '--accent': '#0073FF',
      '--ink': '#232323',
      '--surface': '#ffffff',
      '--chrome-bg': '#000000',
      '--chrome-text': '#ffffff',
    },
    supportCenter: 'Bloomberg Law Help Desk',
    disclaimer: 'NOT ACTUALLY A BLOOMBERG LAW SITE — internal demo only, not affiliated with, endorsed by, or a real Bloomberg Industry Group product.',
  },
  '4b663efb': {
    slug: '4b663efb',
    company: 'Nordstrom',
    brandMark: 'N',
    vertical: 'marketplace',
    hideRibbon: true,
    oncallOnly: true,
    page: {
      file: '4b663efb.html',
      title: 'On Cloudsurfer 2 Running Shoe (Women) | Nordstrom',
    },
    accent: '#191A1B',
    accentDark: '#000000',
    theme: {
      '--accent': '#191A1B',
      '--ink': '#191A1B',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#000000',
      '--chrome-text': '#FFFFFF',
    },
    devinSession: { auto: true },
    supportCenter: 'Nordstrom Customer Care',
    supportCenterSub: 'Online Orders & Shopping Bag',
    disclaimer: 'NOT ACTUALLY A NORDSTROM SITE — internal demo only, not affiliated with, endorsed by, or a real Nordstrom product.',
  },
  '9cb2eced': {
    slug: '9cb2eced',
    company: 'Singapore Airlines',
    brandMark: 'SQ',
    vertical: 'marketplace',
    hideRibbon: true,
    oncallOnly: true,
    page: {
      file: '9cb2eced.html',
      title: 'Singapore Airlines Official Website | Book International Flight Tickets',
    },
    accent: '#00266B',
    accentDark: '#001D52',
    theme: {
      '--accent': '#00266B',
      '--ink': '#222222',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#00266B',
      '--chrome-text': '#FFFFFF',
    },
    devinSession: { auto: true },
    supportCenter: 'Singapore Airlines Support',
    supportCenterSub: 'Flight Booking & KrisFlyer Support',
    disclaimer: 'NOT ACTUALLY A SINGAPORE AIRLINES SITE — internal demo only, not affiliated with, endorsed by, or a real Singapore Airlines product.',
    bugPortal: {
      products: [
        {
          area: 'marketplace',
          label: 'Singapore Airlines \u2014 Book flight',
          persona: { name: 'Priya Nair', email: 'priya.nair@brightmail.io', sev: 'High' },
          templates: [
            {
              id: 'marketplace-cart-timeout',
              label: 'Flight search fails with a timeout',
              sev: 'High',
              text: 'Customers cannot search for flights. You press "Search" on Book trip, the button spins for about eight seconds and then an error comes back saying seat availability could not be checked. Same route, same dates, every attempt.',
            },
            {
              id: 'marketplace-campaign-conversion',
              label: 'Fare sale traffic converting at zero',
              sev: 'Critical',
              text: 'Escalating from revenue management: the Europe fare sale is live, traffic is fine and the homepage loads, but bookings have collapsed to almost nothing. Every search we try ourselves spins for ages and then errors out. We are burning media spend on a booking flow that cannot return a fare.',
            },
          ],
        },
      ],
    },
  },
  '14fa2049': {
    slug: '14fa2049',
    company: 'CapitaLand',
    brandMark: 'C',
    vertical: 'marketplace',
    oncallOnly: true,
    page: {
      file: '14fa2049.html',
      title: 'eCapitaVoucher S$50 | CapitaStar eStore | CapitaLand Malls',
    },
    accent: '#00238B',
    accentDark: '#001A68',
    theme: {
      '--accent': '#00238B',
      '--ink': '#292929',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#00238B',
      '--chrome-text': '#FFFFFF',
    },
    supportCenter: 'CapitaLand Malls Support',
    supportCenterSub: 'CapitaStar eStore & eCapitaVoucher',
    disclaimer: 'NOT ACTUALLY A CAPITALAND SITE — internal demo only, not affiliated with, endorsed by, or a real CapitaLand product.',
  },
  '5d7c46c1': {
    slug: '5d7c46c1',
    company: 'Figure',
    brandMark: 'F',
    vertical: 'banking',
    page: { file: '5d7c46c1.html', title: 'Request a draw | Figure HELOC' },
    theme: {
      '--accent': '#5B56F5',
      '--ink': '#1A1B22',
      '--surface': '#ffffff',
      '--chrome-bg': '#1A1B22',
      '--chrome-text': '#ffffff',
    },
    supportCenter: 'Figure Support',
    disclaimer: 'NOT ACTUALLY A FIGURE SITE — internal demo only, not affiliated with, endorsed by, or a real Figure Lending LLC product.',
  },
  '871f5f7f': {
    slug: '871f5f7f',
    company: 'Turnitin',
    brandMark: 'T',
    vertical: 'hightech',
    page: {
      file: '871f5f7f.html',
      title: 'License management | Turnitin',
    },
    accent: '#0DFFAD',
    accentDark: '#04E69A',
    theme: {
      '--accent': '#0096FF',
      '--ink': '#003C46',
      '--surface': '#ffffff',
      '--chrome-bg': '#003C46',
      '--chrome-text': '#ffffff',
    },
    supportCenter: 'Turnitin Support',
    supportCenterSub: 'Administrator & Instructor Support',
    disclaimer: 'NOT ACTUALLY A TURNITIN SITE — internal demo only, not affiliated with, endorsed by, or a real Turnitin product.',
  },
  '42d69b95': {
    slug: '42d69b95',
    company: 'Rippling',
    brandMark: 'R',
    vertical: 'hightech',
    page: { file: '42d69b95.html', title: 'Assign apps | App Management – Rippling IT' },
    theme: {
      '--accent': '#FFA81D',
      '--ink': '#1C1C1C',
      '--surface': '#ffffff',
      '--chrome-bg': '#4A0039',
      '--chrome-text': '#ffffff',
    },
    supportCenter: 'Rippling Help Center',
    disclaimer: 'NOT ACTUALLY A RIPPLING SITE — internal demo only, not affiliated with, endorsed by, or a real Rippling People Center Inc. product.',
  },
  '347abdf0': {
    slug: '347abdf0',
    company: 'Hebbia',
    brandMark: 'H',
    vertical: 'hightech',
    page: { file: '347abdf0.html', title: 'Add seats | Matrix workspaces – Hebbia' },
    theme: {
      '--accent': '#465BFF',
      '--ink': '#0E0B0B',
      '--surface': '#ffffff',
      '--chrome-bg': '#0E0B0B',
      '--chrome-text': '#F4F1EB',
    },
    supportCenter: 'Hebbia Support',
    disclaimer: 'NOT ACTUALLY A HEBBIA SITE — internal demo only, not affiliated with, endorsed by, or a real Hebbia product.',
  },
  '7fcd58da': {
    slug: '7fcd58da',
    company: 'Rabobank',
    brandMark: 'R',
    vertical: 'banking',
    page: { file: '7fcd58da.html', title: 'Overboeken | Rabo Online Bankieren – Rabobank' },
    theme: {
      '--accent': '#FA6400',
      '--ink': '#202122',
      '--surface': '#ffffff',
      '--chrome-bg': '#000061',
      '--chrome-text': '#ffffff',
    },
    supportCenter: 'Rabobank Klantenservice',
    disclaimer: 'NOT ACTUALLY A RABOBANK SITE — internal demo only, not affiliated with, endorsed by, or a real Rabobank product.',
  },
  '85b32278': {
    slug: '85b32278',
    company: 'PostNL',
    brandMark: 'P',
    vertical: 'insurance',
    page: { file: '85b32278.html', title: 'Schade melden | PostNL' },
    theme: {
      '--accent': '#6161FF',
      '--ink': '#1F1E2F',
      '--surface': '#ffffff',
      '--chrome-bg': '#001A73',
      '--chrome-text': '#ffffff',
    },
    supportCenter: 'PostNL Klantenservice',
    disclaimer: 'NOT ACTUALLY A POSTNL SITE — internal demo only, not affiliated with, endorsed by, or a real PostNL product.',
  },
  '3659ea4f': {
    slug: '3659ea4f',
    company: 'Kela',
    brandMark: 'K',
    vertical: 'hightech',
    page: { file: '3659ea4f.html', title: 'Operator access | Kela Perimeter Command & Control' },
    theme: {
      '--accent': '#00E6FF',
      '--ink': '#181825',
      '--surface': '#F1F0EE',
      '--chrome-bg': '#181825',
      '--chrome-text': '#F1F0EE',
    },
    supportCenter: 'Kela Support',
    disclaimer: 'NOT ACTUALLY A KELA SITE — internal demo only, not affiliated with, endorsed by, or a real Kela product.',
  },
  '0e315106': {
    slug: '0e315106',
    company: 'Rootly',
    brandMark: 'R',
    vertical: 'hightech',
    hideRibbon: true,
    oncallOnly: true,
    page: {
      file: '0e315106.html',
      title: 'Provision responder seats | Rootly',
    },
    accent: '#7748F6',
    theme: {
      '--accent': '#7748F6',
      '--ink': '#1E1A33',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#1E1A33',
      '--chrome-text': '#FFFFFF',
    },
    devinSession: { auto: true },
    supportCenter: 'Rootly Support',
    supportCenterSub: 'Workspace & On-Call Administration',
    disclaimer: 'NOT ACTUALLY A ROOTLY SITE — internal demo only, not affiliated with, endorsed by, or a real Rootly Inc. product.',
  },
  '5626e47f': {
    slug: '5626e47f',
    company: 'Solocal',
    brandMark: 'S',
    vertical: 'telco',
    page: {
      file: '5626e47f.html',
      title: 'Solocal Manager — Mon offre pagesjaunes',
    },
    theme: {
      '--accent': '#0A68F1',
      '--ink': '#0B1B2B',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#0B1B2B',
      '--chrome-text': '#F7F9FC',
    },
    supportCenter: 'Solocal Support',
    disclaimer: 'NOT ACTUALLY A SOLOCAL SITE — internal demo only, not affiliated with, endorsed by, or a real Solocal product.',
  },
  '3555266e': {
    slug: '3555266e',
    company: 'Revolut',
    brandMark: 'R',
    vertical: 'banking',
    page: { file: '3555266e.html', title: 'International Transfers | Revolut US' },
    theme: {
      '--accent': '#1F1F1F',
      '--ink': '#1F1F1F',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#191C1F',
      '--chrome-text': '#FFFFFF',
    },
    supportCenter: 'Revolut Support',
    disclaimer: 'NOT ACTUALLY A REVOLUT SITE — internal demo only, not affiliated with, endorsed by, or a real Revolut product.',
  },
  '8bc7a017': {
    slug: '8bc7a017',
    company: 'Evercore',
    brandMark: 'E',
    vertical: 'banking',
    page: {
      file: '8bc7a017.html',
      title: 'Evercore — Client Portal | Move Money',
    },
    accent: '#1D4289',
    accentDark: '#16336A',
    theme: {
      '--accent': '#1D4289',
      '--ink': '#212121',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#002037',
      '--chrome-text': '#FFFFFF',
    },
    supportCenter: 'Evercore Client Service',
    supportCenterSub: 'Wealth Management & Trust Company',
    disclaimer: 'NOT ACTUALLY AN EVERCORE SITE — internal demo only, not affiliated with, endorsed by, or a real Evercore product.',
  },
  '20d592fb': {
    slug: '20d592fb',
    company: 'Evercore',
    brandMark: 'E',
    vertical: 'banking',
    page: { file: '20d592fb.html', title: 'Sales & Trading - Evercore' },
    theme: {
      '--accent': '#1D4289',
      '--ink': '#151B1F',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#002037',
      '--chrome-text': '#FFFFFF',
    },
    supportCenter: 'Evercore ISI Client Service',
    supportCenterSub: 'Sales & Trading Desk Support',
    disclaimer: 'NOT ACTUALLY AN EVERCORE SITE — internal demo only, not affiliated with, endorsed by, or a real Evercore product.',
  },
  'e7f54d10': {
    slug: 'e7f54d10',
    company: 'InstaLILY',
    brandMark: 'IL',
    vertical: 'hightech',
    page: {
      file: 'e7f54d10.html',
      title: 'InstaControl™ — Agent seats | InstaLILY',
    },
    theme: {
      '--accent': '#2E6B45',
      '--ink': '#0A0A0A',
      '--surface': '#F2F3EC',
      '--chrome-bg': '#0A0A0A',
      '--chrome-text': '#F2F3EC',
    },
    supportCenter: 'InstaLILY Support',
    disclaimer: 'NOT ACTUALLY AN INSTALILY SITE — internal demo only, not affiliated with, endorsed by, or a real InstaLILY product.',
  },
  'f6ea705e': {
    slug: 'f6ea705e',
    company: 'Adonis',
    brandMark: 'a',
    vertical: 'insurance',
    page: { file: 'f6ea705e.html', title: 'Submit claim to payer | Adonis' },
    theme: {
      '--accent': '#074141',
      '--ink': '#0D0D12',
      '--surface': '#ffffff',
      '--chrome-bg': '#042F3A',
      '--chrome-text': '#ffffff',
    },
    supportCenter: 'Adonis Support',
    disclaimer: 'NOT ACTUALLY AN ADONIS SITE — internal demo only, not affiliated with, endorsed by, or a real Adonis product.',
  },
  '28e47b87': {
    slug: '28e47b87',
    company: 'Vanguard',
    brandMark: 'V',
    vertical: 'banking',
    page: {
      // Natively branded custom page: served instead of the vertical's stock
      // page, so the brand shim skips the title/logo rewrite. Keep the file's
      // own <title> in sync with page.title.
      file: '28e47b87.html',
      title: 'Balances and holdings | Vanguard',
    },
    accent: '#96151D',
    accentDark: '#7A1017',
    theme: {
      '--accent': '#96151D',
      '--ink': '#1A1A1A',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#96151D',
      '--chrome-text': '#FFFFFF',
    },
    devinSession: { auto: true },
    supportCenter: 'Vanguard Client Services',
    supportCenterSub: 'Personal Investor Care & Incident Intake',
    disclaimer: 'NOT ACTUALLY A VANGUARD SITE — internal demo only, not affiliated with, endorsed by, or a real Vanguard product.',
  },
  '848b5205': {
    slug: '848b5205',
    company: 'ZKB',
    brandMark: 'Z',
    vertical: 'banking',
    page: {
      // Natively branded custom page: served instead of the vertical's stock
      // page, so the brand shim skips the title/logo rewrite. Keep the file's
      // own <title> in sync with page.title.
      file: '848b5205.html',
      title: 'Zahlungen | ZKB eBanking',
    },
    accent: '#003CB4',
    accentDark: '#002F8E',
    theme: {
      '--accent': '#003CB4',
      '--ink': '#1A1A1A',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#080F5E',
      '--chrome-text': '#FFFFFF',
    },
    supportCenter: 'ZKB Kundenservice',
    supportCenterSub: 'eBanking Support & Incident Intake',
    disclaimer: 'NOT ACTUALLY A ZKB SITE — internal demo only, not affiliated with, endorsed by, or a real ZKB product.',
  },
  '763a0ead': {
    slug: '763a0ead',
    company: 'Adyen',
    brandMark: 'A',
    vertical: 'banking',
    page: {
      // Natively branded custom page: served instead of the vertical's stock
      // page, so the brand shim skips the title/logo rewrite. Keep the file's
      // own <title> in sync with page.title.
      file: '763a0ead.html',
      title: 'Payouts | Adyen Customer Area',
    },
    accent: '#00D16A',
    accentDark: '#00A855',
    theme: {
      '--accent': '#00D16A',
      '--ink': '#0D1E2E',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#001222',
      '--chrome-text': '#FFFFFF',
    },
    supportCenter: 'Adyen Support',
    supportCenterSub: 'Customer Area Support & Incident Intake',
    disclaimer: 'NOT ACTUALLY AN ADYEN SITE — internal demo only, not affiliated with, endorsed by, or a real Adyen product.',
  },
  'a75ccde9': {
    slug: 'a75ccde9',
    company: 'FOX One',
    brandMark: 'F',
    vertical: 'telco',
    devinSession: {
      auto: true,
      promptAppendix: [
        'Proof requirements for this incident (customer-facing web page):',
        '1. Start a screen recording with recording_start before you change any code — the recording is a required deliverable. Then reproduce the failure in the browser at the live page above: click the "Annual" billing toggle and capture a screenshot of the failed state.',
        '2. After the fix, run the app locally on your branch, repeat the same action on http://localhost:<port>/oncall/c/a75ccde9 and capture a screenshot of the successful state.',
        '3. Keep recording across both passes so the before (live failure) and after (local fix) play back to back, annotate each pass with annotate_recording, then recording_stop. Attach the recording and both screenshots to the PR description and post the PR link here.',
        '4. Do not merge; stop for human approval after Devin Review runs.',
      ].join('\n'),
    },
    page: { file: 'a75ccde9.html', title: 'Change Your Plan | FOX One' },
    theme: {
      '--accent': '#000000',
      '--ink': '#1A1A1A',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#000000',
      '--chrome-text': '#FFFFFF',
    },
    supportCenter: 'FOX One Help',
    disclaimer: 'NOT ACTUALLY A FOX ONE SITE — internal demo only, not affiliated with, endorsed by, or a real FOX / Fox Media LLC product.',
  },
  '3983a181': {
    slug: '3983a181',
    company: 'British Airways',
    brandMark: 'BA',
    vertical: 'banking',
    oncallOnly: true,
    page: { file: '3983a181.html', title: 'Payment | British Airways' },
    theme: {
      '--accent': '#3468AD',
      '--ink': '#021B41',
      '--surface': '#F9F9FA',
      '--chrome-bg': '#01122C',
      '--chrome-text': '#FFFFFF',
    },
    supportCenter: 'British Airways Help Centre',
    disclaimer: 'NOT ACTUALLY A BRITISH AIRWAYS SITE — internal demo only, not affiliated with, endorsed by, or a real British Airways product.',
  },
  '30922028': {
    slug: '30922028',
    company: 'GovTech Singapore',
    brandMark: 'P',
    vertical: 'banking',
    oncallOnly: true,
    page: { file: '30922028.html', title: 'Pay | PaySG' },
    theme: {
      '--accent': '#1E51D4',
      '--ink': '#333A4A',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#151D31',
      '--chrome-text': '#FFFFFF',
    },
    supportCenter: 'PaySG Support',
    disclaimer: 'NOT ACTUALLY A GOVTECH SINGAPORE SITE — internal demo only, not affiliated with, endorsed by, or a real GovTech Singapore product.',
  },
  '696c04ec': {
    slug: '696c04ec',
    company: 'Careem',
    brandMark: 'C',
    vertical: 'banking',
    page: {
      file: '696c04ec.html',
      title: 'Send money abroad | Careem Pay',
    },
    accent: '#00EB79',
    accentDark: '#00C965',
    theme: {
      '--accent': '#00EB79',
      '--ink': '#1F2937',
      '--surface': '#ffffff',
      '--chrome-bg': '#001942',
      '--chrome-text': '#ffffff',
    },
    supportCenter: 'Careem Pay Support',
    supportCenterSub: 'Customer Care & Incident Intake',
    disclaimer: 'NOT ACTUALLY A CAREEM SITE — internal demo only, not affiliated with, endorsed by, or a real Careem product.',
  },
  '9dda44d0': {
    slug: '9dda44d0',
    company: 'Strategic Education, Inc.',
    brandMark: 'S',
    vertical: 'hightech',
    page: { file: '9dda44d0.html', title: 'Add learner seats | Education Benefits Management – Strategic Education, Inc.' },
    theme: {
      '--accent': '#DD2A3F',
      '--ink': '#212529',
      '--surface': '#ffffff',
      '--chrome-bg': '#101820',
      '--chrome-text': '#ffffff',
    },
    supportCenter: 'Strategic Education Support',
    disclaimer: 'NOT ACTUALLY A STRATEGIC EDUCATION SITE — internal demo only, not affiliated with, endorsed by, or a real Strategic Education, Inc. product.',
  },
  'ad70f2d2': {
    slug: 'ad70f2d2',
    company: 'Drata',
    brandMark: 'D',
    vertical: 'hightech',
    page: {
      file: 'ad70f2d2.html',
      title: 'Drata — Personnel Provisioning',
    },
    theme: {
      '--accent': '#354ECF',
      '--ink': '#09090A',
      '--surface': '#F5F6F7',
      '--chrome-bg': '#09090A',
      '--chrome-text': '#F5F6F7',
    },
    supportCenter: 'Drata Support',
    disclaimer: 'NOT ACTUALLY A DRATA SITE — internal demo only, not affiliated with, endorsed by, or a real Drata product.',
  },
  '68cde0d3': {
    slug: '68cde0d3',
    company: 'WorkOS',
    brandMark: 'W',
    vertical: 'hightech',
    page: { file: '68cde0d3.html', title: 'WorkOS — Directory Sync' },
    theme: {
      '--accent': '#6363F1',
      '--ink': '#29363D',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#030628',
      '--chrome-text': '#F9F9FB',
    },
    supportCenter: 'WorkOS Support',
    supportCenterSub: 'Enterprise Support & Incident Intake',
    disclaimer: 'NOT ACTUALLY A WORKOS SITE — internal demo only, not affiliated with, endorsed by, or a real WorkOS product.',
  },
  'd2c12d14': {
    slug: 'd2c12d14',
    company: 'Modern Health',
    brandMark: 'M',
    vertical: 'hightech',
    page: { file: 'd2c12d14.html', title: 'Modern Health — Member Access Provisioning' },
    theme: {
      '--accent': '#0069BF',
      '--ink': '#3C3C3C',
      '--surface': '#F8F6EE',
      '--chrome-bg': '#043570',
      '--chrome-text': '#F8F6EE',
    },
    supportCenter: 'Modern Health Support',
    supportCenterSub: 'Employer & Member Support',
    disclaimer: 'NOT ACTUALLY A MODERN HEALTH SITE — internal demo only, not affiliated with, endorsed by, or a real Modern Health product.',
  },
  'ce0199ec': {
    slug: 'ce0199ec',
    company: 'Cross River',
    brandMark: 'C',
    vertical: 'banking',
    page: {
      file: 'ce0199ec.html',
      title: 'Cross River | Payments — Move Money',
    },
    accent: '#00F996',
    accentDark: '#00d67f',
    theme: {
      '--accent': '#1470CC',
      '--ink': '#05112E',
      '--surface': '#ffffff',
      '--chrome-bg': '#05112E',
      '--chrome-text': '#ffffff',
    },
    devinSession: { auto: true },
    sonarPR: { auto: true },
    supportCenter: 'Cross River Support',
    supportCenterSub: 'Payments & Accounts Operations',
    disclaimer: 'NOT ACTUALLY A CROSS RIVER SITE — internal demo only, not affiliated with, endorsed by, or a real Cross River product.',
  },
  '4c8c5b8f': {
    slug: '4c8c5b8f',
    company: 'OCBC',
    brandMark: 'O',
    vertical: 'banking',
    page: {
      file: '4c8c5b8f.html',
      title: 'Fund360 — Place a fund bid | OCBC',
    },
    theme: {
      '--accent': '#E30613',
      '--ink': '#363B40',
      '--surface': '#ffffff',
      '--chrome-bg': '#2D3D45',
      '--chrome-text': '#ffffff',
    },
    supportCenter: 'OCBC Support',
    disclaimer: 'NOT ACTUALLY AN OCBC SITE — internal demo only, not affiliated with, endorsed by, or a real OCBC product.',
  },
  '777b1b03': {
    slug: '777b1b03',
    company: 'Boeing',
    brandMark: 'B',
    vertical: 'industrials',
    page: {
      // Natively branded custom page: served instead of the vertical's stock
      // page; the brand shim skips the title/logo rewrite for it.
      file: '777b1b03.html',
      title: 'Velocity — Nonconformance Submittal | Boeing',
    },
    theme: {
      '--accent': '#0033A1',
      '--ink': '#253746',
      '--surface': '#ffffff',
      '--chrome-bg': '#0A2240',
      '--chrome-text': '#ffffff',
    },
    supportCenter: 'Boeing Support',
    supportCenterSub: 'Quality Systems Support & Incident Intake',
    disclaimer: 'NOT ACTUALLY A BOEING SITE — internal demo only, not affiliated with, endorsed by, or a real Boeing product.',
  },
  '180f1323': {
    slug: '180f1323',
    company: 'MyBoeingFleet',
    brandMark: 'M',
    vertical: 'industrials',
    oncallOnly: true,
    page: {
      file: '180f1323.html',
      title: 'PART Page — Spares price & availability | MyBoeingFleet',
    },
    theme: {
      '--accent': '#009CDE',
      '--ink': '#253746',
      '--surface': '#ffffff',
      '--chrome-bg': '#1D2B36',
      '--chrome-text': '#ffffff',
    },
    supportCenter: 'MyBoeingFleet Support',
    supportCenterSub: 'Parts & Distribution Operator Support',
    disclaimer: 'NOT ACTUALLY A MYBOEINGFLEET SITE — internal demo only, not affiliated with, endorsed by, or a real Boeing product.',
  },
  'bb0a082c': {
    slug: 'bb0a082c',
    company: 'Gap',
    brandMark: 'G',
    vertical: 'banking',
    page: {
      file: 'bb0a082c.html',
      title: 'Checkout | Gap',
    },
    theme: {
      '--accent': '#031BA1',
      '--ink': '#000000',
      '--surface': '#ffffff',
      '--chrome-bg': '#000000',
      '--chrome-text': '#ffffff',
    },
    supportCenter: 'Gap Customer Service',
    disclaimer: 'NOT ACTUALLY A GAP SITE — internal demo only, not affiliated with, endorsed by, or a real Gap product.',
  },
  'afc90dda': {
    slug: 'afc90dda',
    company: 'Zurich',
    brandMark: 'Z',
    vertical: 'insurance',
    page: {
      // Natively branded custom page: served instead of the vertical's stock
      // page; the brand shim skips the title/logo rewrite for it. Keep the
      // file's own <title> in sync with page.title.
      file: 'afc90dda.html',
      title: 'Report a claim | Zurich U.S.',
    },
    theme: {
      '--accent': '#2167AE',
      '--ink': '#23366F',
      '--surface': '#ffffff',
      '--chrome-bg': '#2167AE',
      '--chrome-text': '#ffffff',
    },
    supportCenter: 'Zurich Customer Care Center',
    supportCenterSub: 'Claims Support & Incident Intake',
    disclaimer: 'NOT ACTUALLY A ZURICH SITE — internal demo only, not affiliated with, endorsed by, or a real Zurich product.',
  },
  'd949b852': {
    slug: 'd949b852',
    company: 'LSEG',
    brandMark: 'L',
    vertical: 'banking',
    page: {
      // Natively branded custom page: served instead of the vertical's stock
      // page; the brand shim skips the title/logo rewrite for it. Keep the
      // file's own <title> in sync with page.title.
      file: 'd949b852.html',
      title: 'TradeAgent — Settlement Instructions | LSEG Post Trade',
    },
    theme: {
      '--accent': '#001EFF',
      '--ink': '#4D4D4D',
      '--surface': '#ffffff',
      '--chrome-bg': '#001489',
      '--chrome-text': '#ffffff',
    },
    supportCenter: 'LSEG Post Trade Client Services',
    supportCenterSub: 'TradeAgent Support & Incident Intake',
    disclaimer: 'NOT ACTUALLY AN LSEG SITE — internal demo only, not affiliated with, endorsed by, or a real London Stock Exchange Group product.',
  },
  'e63edc26': {
    slug: 'e63edc26',
    company: 'Harvey',
    brandMark: 'H',
    vertical: 'hightech',
    page: {
      // Natively branded custom page: served instead of the vertical's stock
      // page; the brand shim skips the title/logo rewrite for it. Keep the
      // file's own <title> in sync with page.title.
      file: 'e63edc26.html',
      title: 'Harvey | Workspace Access',
    },
    theme: {
      '--accent': '#0f0e0d',
      '--ink': '#0f0e0d',
      '--surface': '#fafaf9',
      '--chrome-bg': '#0f0e0d',
      '--chrome-text': '#fafaf9',
    },
    supportCenter: 'Harvey Support',
    supportCenterSub: 'Workspace Access & Incident Intake',
    disclaimer: 'NOT ACTUALLY A HARVEY SITE — internal demo only, not affiliated with, endorsed by, or a real Harvey product.',
  },
  '248de71e': {
    slug: '248de71e',
    company: 'bp',
    brandMark: 'bp',
    vertical: 'banking',
    oncallOnly: true,
    page: {
      // Natively branded custom page: served instead of the vertical's stock
      // page; the brand shim skips the title/logo rewrite for it. Keep the
      // file's own <title> in sync with page.title.
      file: '248de71e.html',
      title: 'Pay card balance | bp Business Solutions',
    },
    theme: {
      '--accent': '#007F00',
      '--ink': '#121000',
      '--surface': '#FBFCF8',
      '--chrome-bg': '#004200',
      '--chrome-text': '#FFFFFF',
    },
    supportCenter: 'bp Business Solutions Customer Service',
    disclaimer: 'NOT ACTUALLY A BP SITE — internal demo only, not affiliated with, endorsed by, or a real bp product.',
  },
  '31f02f28': {
    slug: '31f02f28',
    company: 'Erebor',
    brandMark: 'E',
    vertical: 'banking',
    page: {
      // Natively branded custom page: served instead of the vertical's stock
      // page; the brand shim skips the title/logo rewrite for it. Keep the
      // file's own <title> in sync with page.title.
      file: '31f02f28.html',
      title: 'Move money | Erebor',
    },
    theme: {
      '--accent': '#1a1a18',
      '--ink': '#1a1a18',
      '--surface': '#f8f7f4',
      '--chrome-bg': '#000000',
      '--chrome-text': '#f8f7f4',
    },
    supportCenter: 'Erebor Client Service',
    disclaimer: 'NOT ACTUALLY AN EREBOR SITE — internal demo only, not affiliated with, endorsed by, or a real Erebor product.',
  },
  '82b32928': {
    slug: '82b32928',
    company: 'Nebius',
    brandMark: 'N',
    vertical: 'hightech',
    page: {
      file: '82b32928.html',
      title: 'Provision GPUs | Nebius AI Cloud',
    },
    theme: {
      '--accent': '#3277FF',
      '--ink': '#052B42',
      '--surface': '#ffffff',
      '--chrome-bg': '#052B42',
      '--chrome-text': '#ffffff',
    },
    supportCenter: 'Nebius Support',
    supportCenterSub: 'AI Cloud Support & Incident Intake',
    disclaimer: 'NOT ACTUALLY A NEBIUS SITE — internal demo only, not affiliated with, endorsed by, or a real Nebius product.',
  },
  '5afb121f': {
    slug: '5afb121f',
    company: 'Siemens',
    brandMark: 'S',
    vertical: 'hightech',
    oncallOnly: true,
    page: {
      file: '5afb121f.html',
      title: 'Add seats | Siemens Xcelerator',
    },
    theme: {
      '--accent': '#007993',
      '--ink': '#000028',
      '--surface': '#ffffff',
      '--chrome-bg': '#000028',
      '--chrome-text': '#ffffff',
    },
    supportCenter: 'Siemens Support Center',
    supportCenterSub: 'Digital Industries Software Support',
    disclaimer: 'NOT ACTUALLY A SIEMENS SITE — internal demo only, not affiliated with, endorsed by, or a real Siemens product.',
  },
  'd47f7970': {
    slug: 'd47f7970',
    company: 'The Economist',
    brandMark: 'E',
    vertical: 'telco',
    oncallOnly: true,
    page: {
      file: 'd47f7970.html',
      title: 'Manage subscription | The Economist',
    },
    theme: {
      '--accent': '#E3120B',
      '--ink': '#0D0D0D',
      '--surface': '#ffffff',
      '--chrome-bg': '#1A1A1A',
      '--chrome-text': '#ffffff',
    },
    supportCenter: 'The Economist Customer Service',
    supportCenterSub: 'Subscription Support & Incident Intake',
    disclaimer: 'NOT ACTUALLY AN ECONOMIST SITE — internal demo only, not affiliated with, endorsed by, or a real Economist product.',
  },
  'c06e0447': {
    slug: 'c06e0447',
    company: 'zooplus',
    brandMark: 'Z',
    vertical: 'marketplace',
    hideRibbon: true,
    oncallOnly: true,
    page: {
      file: 'c06e0447.html',
      title: '12 kg + 1,5 kg gratis! 13,5 kg Concept for Life Medium Adult | zooplus',
    },
    theme: {
      '--accent': '#278403',
      '--ink': '#323942',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#144700',
      '--chrome-text': '#FFFFFF',
    },
    supportCenter: 'zooplus Kundenservice',
    supportCenterSub: 'Onlineshop & Warenkorb',
    disclaimer: 'NOT ACTUALLY A ZOOPLUS SITE — internal demo only, not affiliated with, endorsed by, or a real zooplus product.',
  },
  '93d48678': {
    slug: '93d48678',
    company: 'Accelya',
    brandMark: 'a',
    vertical: 'banking',
    oncallOnly: true,
    page: {
      file: '93d48678.html',
      title: 'Accelya Payments | Settle an order payment',
    },
    theme: {
      '--accent': '#5CB8B2',
      '--ink': '#425563',
      '--surface': '#FFFFFF',
      '--chrome-bg': '#012169',
      '--chrome-text': '#FFFFFF',
    },
    supportCenter: 'Accelya Support',
    supportCenterSub: 'Payments & order accounting',
    disclaimer: 'NOT ACTUALLY AN ACCELYA SITE — internal demo only, not affiliated with, endorsed by, or a real Accelya product.',
  },
};

function getOncallSkin(slug) {
  if (!slug || typeof slug !== 'string') return null;
  const key = slug.toLowerCase();
  return Object.prototype.hasOwnProperty.call(ONCALL_SKINS, key) ? ONCALL_SKINS[key] : null;
}

module.exports = { ONCALL_SKINS, getOncallSkin };
